const quotes = [
  { text: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "J.R.R. Tolkien" },
  { text: "You have bewitched me, body and soul, and I love, I love, I love you.", author: "Jane Austen" },
  { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
  { text: "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
  { text: "If I had a flower for every time I thought of you, I could walk in my garden forever.", author: "Alfred Lord Tennyson" },
  { text: "You should be kissed and often, and by someone who knows how.", author: "Margaret Mitchell" },
  { text: "He stepped down, trying not to look long at her, as if she were the sun...", author: "Leo Tolstoy" },
  { text: "I am nothing special... But I've loved another with all my heart and soul...", author: "Nicholas Sparks" },
  { text: "So, I love you because the entire universe conspired to help me find you.", author: "Paulo Coelho" },
  { text: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "J.R.R. Tolkien" },
  { text: "You have bewitched me, body and soul, and I love, I love, I love you.", author: "Jane Austen" },
  { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
  { text: "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
  { text: "If I had a flower for every time I thought of you, I could walk in my garden forever.", author: "Alfred Lord Tennyson" },
  { text: "You should be kissed and often, and by someone who knows how.", author: "Margaret Mitchell" },
  { text: "He stepped down, trying not to look long at her, as if she were the sun...", author: "Leo Tolstoy" },
  { text: "I am nothing special... But I've loved another with all my heart and soul...", author: "Nicholas Sparks" },
  { text: "So, I love you because the entire universe conspired to help me find you.", author: "Paulo Coelho" },
  { text: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "J.R.R. Tolkien" },
  { text: "You have bewitched me, body and soul, and I love, I love, I love you.", author: "Jane Austen" },
  { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
  { text: "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
  { text: "If I had a flower for every time I thought of you, I could walk in my garden forever.", author: "Alfred Lord Tennyson" },
  { text: "You should be kissed and often, and by someone who knows how.", author: "Margaret Mitchell" },
  { text: "He stepped down, trying not to look long at her, as if she were the sun...", author: "Leo Tolstoy" },
  { text: "I am nothing special... But I've loved another with all my heart and soul...", author: "Nicholas Sparks" },
  { text: "So, I love you because the entire universe conspired to help me find you.", author: "Paulo Coelho" },
  { text: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "J.R.R. Tolkien" },
  { text: "You have bewitched me, body and soul, and I love, I love, I love you.", author: "Jane Austen" },
  { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
  { text: "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
  { text: "If I had a flower for every time I thought of you, I could walk in my garden forever.", author: "Alfred Lord Tennyson" },
  { text: "You should be kissed and often, and by someone who knows how.", author: "Margaret Mitchell" },
  { text: "He stepped down, trying not to look long at her, as if she were the sun...", author: "Leo Tolstoy" },
  { text: "I am nothing special... But I've loved another with all my heart and soul...", author: "Nicholas Sparks" },
  { text: "So, I love you because the entire universe conspired to help me find you.", author: "Paulo Coelho" },
  { text: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "J.R.R. Tolkien" },
  { text: "You have bewitched me, body and soul, and I love, I love, I love you.", author: "Jane Austen" },
  { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
  { text: "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
  { text: "If I had a flower for every time I thought of you, I could walk in my garden forever.", author: "Alfred Lord Tennyson" },
  { text: "You should be kissed and often, and by someone who knows how.", author: "Margaret Mitchell" },
  { text: "He stepped down, trying not to look long at her, as if she were the sun...", author: "Leo Tolstoy" },
  { text: "I am nothing special... But I've loved another with all my heart and soul...", author: "Nicholas Sparks" },
  { text: "So, I love you because the entire universe conspired to help me find you.", author: "Paulo Coelho" },
  { text: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "J.R.R. Tolkien" },
  { text: "You have bewitched me, body and soul, and I love, I love, I love you.", author: "Jane Austen" },
  { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
  { text: "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
  { text: "If I had a flower for every time I thought of you, I could walk in my garden forever.", author: "Alfred Lord Tennyson" },
  { text: "You should be kissed and often, and by someone who knows how.", author: "Margaret Mitchell" },
  { text: "He stepped down, trying not to look long at her, as if she were the sun...", author: "Leo Tolstoy" },
  { text: "I am nothing special... But I've loved another with all my heart and soul...", author: "Nicholas Sparks" },
  { text: "So, I love you because the entire universe conspired to help me find you.", author: "Paulo Coelho" },
  { text: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "J.R.R. Tolkien" },
  { text: "You have bewitched me, body and soul, and I love, I love, I love you.", author: "Jane Austen" },
  { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
  { text: "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
  { text: "If I had a flower for every time I thought of you, I could walk in my garden forever.", author: "Alfred Lord Tennyson" },
  { text: "You should be kissed and often, and by someone who knows how.", author: "Margaret Mitchell" },
  { text: "He stepped down, trying not to look long at her, as if she were the sun...", author: "Leo Tolstoy" },
  { text: "I am nothing special... But I've loved another with all my heart and soul...", author: "Nicholas Sparks" },
  { text: "So, I love you because the entire universe conspired to help me find you.", author: "Paulo Coelho" },
  { text: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "J.R.R. Tolkien" },
  { text: "You have bewitched me, body and soul, and I love, I love, I love you.", author: "Jane Austen" },
  { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
  { text: "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
  { text: "If I had a flower for every time I thought of you, I could walk in my garden forever.", author: "Alfred Lord Tennyson" },
  { text: "You should be kissed and often, and by someone who knows how.", author: "Margaret Mitchell" },
  { text: "He stepped down, trying not to look long at her, as if she were the sun...", author: "Leo Tolstoy" },
  { text: "I am nothing special... But I've loved another with all my heart and soul...", author: "Nicholas Sparks" },
  { text: "So, I love you because the entire universe conspired to help me find you.", author: "Paulo Coelho" },
  { text: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "J.R.R. Tolkien" },
  { text: "You have bewitched me, body and soul, and I love, I love, I love you.", author: "Jane Austen" },
  { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
  { text: "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
  { text: "If I had a flower for every time I thought of you, I could walk in my garden forever.", author: "Alfred Lord Tennyson" },
  { text: "You should be kissed and often, and by someone who knows how.", author: "Margaret Mitchell" },
  { text: "He stepped down, trying not to look long at her, as if she were the sun...", author: "Leo Tolstoy" },
  { text: "I am nothing special... But I've loved another with all my heart and soul...", author: "Nicholas Sparks" },
  { text: "So, I love you because the entire universe conspired to help me find you.", author: "Paulo Coelho" },
  { text: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "J.R.R. Tolkien" },
  { text: "You have bewitched me, body and soul, and I love, I love, I love you.", author: "Jane Austen" },
  { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
  { text: "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
  { text: "If I had a flower for every time I thought of you, I could walk in my garden forever.", author: "Alfred Lord Tennyson" },
  { text: "You should be kissed and often, and by someone who knows how.", author: "Margaret Mitchell" },
  { text: "He stepped down, trying not to look long at her, as if she were the sun...", author: "Leo Tolstoy" },
  { text: "I am nothing special... But I've loved another with all my heart and soul...", author: "Nicholas Sparks" },
  { text: "So, I love you because the entire universe conspired to help me find you.", author: "Paulo Coelho" },
  { text: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "J.R.R. Tolkien" },
  { text: "You have bewitched me, body and soul, and I love, I love, I love you.", author: "Jane Austen" },
  { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
  { text: "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
  { text: "If I had a flower for every time I thought of you, I could walk in my garden forever.", author: "Alfred Lord Tennyson" },
  { text: "You should be kissed and often, and by someone who knows how.", author: "Margaret Mitchell" },
  { text: "He stepped down, trying not to look long at her, as if she were the sun...", author: "Leo Tolstoy" },
  { text: "I am nothing special... But I've loved another with all my heart and soul...", author: "Nicholas Sparks" },
  { text: "So, I love you because the entire universe conspired to help me find you.", author: "Paulo Coelho" },
  { text: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "J.R.R. Tolkien" },
  { text: "You have bewitched me, body and soul, and I love, I love, I love you.", author: "Jane Austen" },
  { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
  { text: "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
  { text: "If I had a flower for every time I thought of you, I could walk in my garden forever.", author: "Alfred Lord Tennyson" },
  { text: "You should be kissed and often, and by someone who knows how.", author: "Margaret Mitchell" },
  { text: "He stepped down, trying not to look long at her, as if she were the sun...", author: "Leo Tolstoy" },
  { text: "I am nothing special... But I've loved another with all my heart and soul...", author: "Nicholas Sparks" },
  { text: "So, I love you because the entire universe conspired to help me find you.", author: "Paulo Coelho" },
  { text: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "J.R.R. Tolkien" },
  { text: "You have bewitched me, body and soul, and I love, I love, I love you.", author: "Jane Austen" },
  { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
  { text: "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
  { text: "If I had a flower for every time I thought of you, I could walk in my garden forever.", author: "Alfred Lord Tennyson" },
  { text: "You should be kissed and often, and by someone who knows how.", author: "Margaret Mitchell" },
  { text: "He stepped down, trying not to look long at her, as if she were the sun...", author: "Leo Tolstoy" },
  { text: "I am nothing special... But I've loved another with all my heart and soul...", author: "Nicholas Sparks" },
  { text: "So, I love you because the entire universe conspired to help me find you.", author: "Paulo Coelho" },
  { text: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "J.R.R. Tolkien" },
  { text: "You have bewitched me, body and soul, and I love, I love, I love you.", author: "Jane Austen" },
  { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
  { text: "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
  { text: "If I had a flower for every time I thought of you, I could walk in my garden forever.", author: "Alfred Lord Tennyson" },
  { text: "You should be kissed and often, and by someone who knows how.", author: "Margaret Mitchell" },
  { text: "He stepped down, trying not to look long at her, as if she were the sun...", author: "Leo Tolstoy" },
  { text: "I am nothing special... But I've loved another with all my heart and soul...", author: "Nicholas Sparks" },
  { text: "So, I love you because the entire universe conspired to help me find you.", author: "Paulo Coelho" },
  { text: "I would rather share one lifetime with you than face all the ages of this world alone.", author: "J.R.R. Tolkien" },
  { text: "You have bewitched me, body and soul, and I love, I love, I love you.", author: "Jane Austen" },
  { text: "Whatever our souls are made of, his and mine are the same.", author: "Emily Brontë" },
  { text: "As he read, I fell in love the way you fall asleep: slowly, and then all at once.", author: "John Green" },
  { text: "We loved with a love that was more than love.", author: "Edgar Allan Poe" },
  { text: "If I had a flower for every time I thought of you, I could walk in my garden forever.", author: "Alfred Lord Tennyson" },
  { text: "You should be kissed and often, and by someone who knows how.", author: "Margaret Mitchell" },
  { text: "He stepped down, trying not to look long at her, as if she were the sun...", author: "Leo Tolstoy" },
  { text: "I am nothing special... But I've loved another with all my heart and soul...", author: "Nicholas Sparks" },
  { text: "So, I love you because the entire universe conspired to help me find you.", author: "Paulo Coelho" },
];

const randomQuote = quotes[Math.floor(Math.random() * quotes.length)];
document.getElementById("quoteBox").innerHTML = `“${randomQuote.text}”<br><br>— <em>${randomQuote.author}</em>`;